    - name: deploy_pick_n_place_to_ur5e_cell_with_rostooling_rwu_laptop
      hosts: rwu_laptop
      vars:
          docker_compose_dir: rwu_laptop
          ori_docker_compose_dir_path: "../{{ docker_compose_dir }}"
          dest_docker_compose_dir_path: "home/{{ ansible_user }}/AutoDeployment/deploy_pick_n_place_to_ur5e_cell_with_rostooling/{{ docker_compose_dir }}"
      roles:
          - common
          - deploy_software
